### ISSUE TITLE
Figma Design Token Export (types) do not match with style-dictionary-utils  

### ISSUE THREAD

**Issue by the-ult** [lukasoppermann/style-dictionary-utils#35]
When using [Figma Design Tokens plugin](https://github.com/lukasoppermann/design-tokens/) the `type` for typography/font is `"type": "custom-fontStyle"` and for effect (elevation/shadow) the type is: `"type": "custom-shadow";`

But the [font/css](https://github.com/lukasoppermann/style-dictionary-utils#fontcss) is looking for `"type": "typography"` and [shadow/css](https://github.com/lukasoppermann/style-dictionary-utils#shadowcss) for `"type": "shadow"` 

Is there a way to adjust the generated type in Figma? Or make sure style-dictionary-utils works better with the Figma Design Tokens plugin?

### generated tokens.json
```json
{
  heading1": {
    "type": "custom-fontStyle", // THIS SHOULD BE "typography"
    "value": {
      "fontSize": 36,
      "textDecoration": "none",
      "fontFamily": "Lexend",
      "fontWeight": 600,
      "fontStyle": "normal",
      "fontStretch": "normal",
      "letterSpacing": 0,
      "lineHeight": 48,
      "paragraphIndent": 0,
      "paragraphSpacing": 0,
      "textCase": "none"
    },
    "fontSize": {
      "type": "dimension",
      "value": 36
    },
    "textDecoration": {
      "type": "string",
      "value": "none"
    },
    "fontFamily": {
      "type": "string",
      "value": "Lexend"
    },
    "fontWeight": {
      "type": "number",
      "value": 600
    },
    "fontStyle": {
      "type": "string",
      "value": "normal"
    },
    "fontStretch": {
      "type": "string",
      "value": "normal"
    },
    "letterSpacing": {
      "type": "dimension",
      "value": 0
    },
    "lineHeight": {
      "type": "dimension",
      "value": 48
    },
    "paragraphIndent": {
      "type": "dimension",
      "value": 0
    },
    "paragraphSpacing": {
      "type": "dimension",
      "value": 0
    },
    "textCase": {
      "type": "string",
      "value": "none"
    }
  },
  "elevation-1": {
    "0": {
      "type": "custom-shadow", // THIS SHOULD BE "shadow"
      "value": {
        "shadowType": "dropShadow",
        "radius": 3,
        "color": "#00295733",
        "offsetX": 0,
        "offsetY": 1,
        "spread": 0
      }
    },
    "1": {
      "type": "custom-shadow",
      "value": {
        "shadowType": "dropShadow",
        "radius": 2,
        "color": "#0029571f",
        "offsetX": 0,
        "offsetY": 2,
        "spread": 0
      }
    },
    "2": {
      "type": "custom-shadow",
      "value": {
        "shadowType": "dropShadow",
        "radius": 2,
        "color": "#00295724",
        "offsetX": 0,
        "offsetY": 0,
        "spread": 0
      }
    },
    "description": null
  },
}
``` 
this results in:
```css
root {
  --heading1: [object Object];
  --heading2: [object Object];
  --heading3: [object Object];
  --heading4: [object Object];
  --heading5: [object Object];
  --heading6: [object Object];
  --body1: [object Object];
  --body2: [object Object];
  --button: [object Object];
  --caption: [object Object];
}
```

after renaming to `"type": "typography"`:
```css
:root {
  --heading1: normal 600 36/48 Lexend;
  --heading2: normal 600 28/32 Lexend;
  --heading3: normal 600 24/32 Lexend;
  --heading4: normal 600 20/32 Lexend;
  --heading5: normal 600 16/24 Lexend;
  --heading6: normal 600 14/20 Lexend;
  --body1: normal 300 16/24 Lexend;
  --body2: normal 300 14/20 Lexend;
  --button: normal 600 16/24 Lexend;
  --caption: normal 300 12/16 Lexend;
}
```

**N.B.**
Or should [design-token-transformer](https://github.com/lukasoppermann/design-token-transformer) be used? Which doesn't seem to be as easy to use as this library.
